### ISSUE TITLE
Upload file as input

### ISSUE THREAD

**Issue by sithik4git** [boasiHQ/interactive-inputs#5]
Hi, looks useful to give customized UI for getting input fields.
Can it be enhanced to support File upload as input fields..
Currently GH actions is not supporting. 
Actually it should resolve the feature request here. https://github.com/orgs/community/discussions/49612

**Comment by ooaklee** [comment]
Hey @sithik4git, thanks for the suggestions!

The UI  for visualising the portal based on the fields provided or vice versa has crossed my mind a couple of times; let me scope it out properly and see how soon I can get a beta out. 

Regarding the file input type support, that's a good shout. How would you use the feature? Playing around with a potential flow in my head, the initial version could have an output that points to the path of the dir that holds the files uploaded, what are your thoughts on that?

**Comment by ooaklee** [comment]
@sithik4git 

 Later today, I will release a new version with a feature that supports the types `file` and `multifile`. In the initial version, users will be able to:

- Specify whether the field is required
- Restrict the types of files that can be uploaded
- Upload a single file (`file`) or multiple files (`multifile`)

Similar to other input fields, the **output** identifier will use the label declared when defining the interactive fields the portal should have. Note that for any defined `file` and `multifile` input types, the output will return the path to the directory containing the uploaded file(s).

![InteractiveInputs_FileInputTypeSupport](https://github.com/user-attachments/assets/ebd5d34f-7efb-4d2e-83f8-b5d9615dd126)

**Comment by ooaklee** [comment]
@sithik4git the `file` input type has been released at https://github.com/boasiHQ/interactive-inputs/releases/tag/v2.3.0

More information on the `file` and `multifile` field types can be [found in the README](https://github.com/boasiHQ/interactive-inputs?tab=readme-ov-file#multifile-input---multifile)

I've also split the request for a UI renderer into its [**own issue**](https://github.com/boasiHQ/interactive-inputs/issues/7). Please upvote when you get a moment.

**Comment by ooaklee** [comment]
[Shared](https://github.com/orgs/community/discussions/49612#discussioncomment-10587719) with community feature request

**Comment by sithik4git** [comment]
Hey @ooaklee,
Thank you for the quick release of the feature. This will surely help me to unblock something I am working on.
Let me try testing this and revert for any queries. Thanks again!

**Comment by ooaklee** [comment]
No problem @sithik4git. Thanks for requesting such a great feature; it would have been a while before I got around to it myself without the request 😅

> You can probably use https://github.com/boasiHQ/interactive-inputs?#example-workflow-with-all-field-types to reference how you can leverage the input field type. Below, I've pulled out the unrelated bits (I hope it helps)
>
> ```yaml
> name: '[Example] Interactive Inputs - Files flow'
> 
> on:
>   push:
> 
> jobs:
>   interactive-inputs:
>     timeout-minutes: 3
>     runs-on: ubuntu-latest
>     permissions:
>       contents: write
>       actions: write
>     steps:
>       - name: Example Interactive Inputs Step
>         id: interactive-inputs
>         uses: boasihq/interactive-inputs@v2
>         with:
>           ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
>           notifier-slack-enabled: "false"
>           notifier-slack-channel: "#notificaitons"
>           notifier-slack-token: ${{ secrets.SLACK_TOKEN }}
>           notifier-slack-thread-ts: ""
>           notifier-discord-enabled: "false"
>           notifier-discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
>           notifier-discord-thread-id: ""
>           timeout: 300
>           title: 'A batch of 10 feature flags have been added to be deployed. Would you like to proceed?'
>           interactive: |
>             fields:
>               - label: requested-files
>                 properties:
>                   display: Upload desired files
>                   type: multifile
>                   required: true
>                   description: Select the media you wish to upload to this running job
> 
>       - name: List the uploaded files in the directory
>         shell: bash
>         run: |
>           echo "Display uploaded files"
>           echo -e "\n==============================\n"
>           ls -la ${{ steps.interactive-inputs.outputs.requested-files }} # Use the label of the multifile/file field as the key to get the uploaded file directory
>           echo -e "\n==============================\n"


And yeah, please reach out with any queries, and if you need to jump on a call or anything, give me a shout.

**Comment by sithik4git** [comment]
Hi @ooaklee 
Once again, thanks for your continuous support on this feature!
Yeah, when it comes for html form, support of file upload cannot be avoided.

will reach you definitely for any regarding this.
